const photos = [
    // LANDSCAPE ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    { id: 1, src: "/photofolio/bahamas/IMG_0323.JPG", country: "Bahamas", city: "Nassau", lat: 25.04, lng: -77.3, year: 2021, category: "landscape", featured: false },
    { id: 2, src: "/photofolio/usa/IMG_5073 2.jpg", country: "Colorado", city: "Red Rocks Park", lat: 39.66, lng: -105.2, year: 2025, category: "landscape", featured: false },
    { id: 3, src: "/photofolio/usa/IMG_5075.jpg", country: "California", city: "Newport Beach", lat: 33.62, lng: -117.94, year: 2025, category: "landscape", featured: false },
    { id: 4, src: "/photofolio/usa/DSC00910.JPG", country: "California", city: "Newport Beach", lat: 33.62, lng: -117.94, year: 2025, category: "landscape", featured: false },
    { id: 5, src: "/photofolio/portugal/DSC02283.JPG", country: "Portugal", city: "Seven Hanging Valleys", lat: 37.090, lng: -8.2, year: 2025, category: "landscape", featured: false },
    { id: 6, src: "/photofolio/portugal/DSC02552.JPG", country: "Portugal", city: "Seven Hanging Valleys", lat: 37.093, lng: -8.21, year: 2025, category: "landscape", featured: true },
    { id: 7, src: "/photofolio/portugal/DSC02615.JPG", country: "Portugal", city: "Seven Hanging Valleys", lat: 37.089, lng: -8.22, year: 2025, category: "landscape", featured: false },
    { id: 8, src: "/photofolio/portugal/DSC02534.JPG", country: "Portugal", city: "Seven Hanging Valleys", lat: 37.088, lng: -8.23, year: 2025, category: "landscape", featured: true },
    { id: 9, src: "/photofolio/italy/DSC03257.JPG", country: "Italy", city: "Lake Como", lat: 46, lng: 9.293, year: 2025, category: "landscape", featured: false },
    { id: 10, src: "/photofolio/italy/DSC03244.JPG", country: "Italy", city: "Lake Como", lat: 45.99, lng: 9.295, year: 2025, category: "landscape", featured: false },
    { id: 11, src: "/photofolio/ireland/DSC04136.JPG", country: "Ireland", city: "Cliffs of Moher", lat: 53.015, lng: -9.399, year: 2025, category: "landscape", featured: true },
    { id: 12, src: "/photofolio/ireland/DSC03798.JPG", country: "Ireland", city: "Howth Cliff", lat: 53.4, lng: -6.1, year: 2025, category: "landscape", featured: true },
    { id: 13, src: "/photofolio/ireland/DSC04133.JPG", country: "Ireland", city: "Cliffs of Moher", lat: 53.013, lng: -9.398, year: 2025, category: "landscape", featured: false },
    { id: 14, src: "/photofolio/ireland/DSC04158.JPG", country: "Ireland", city: "Cliffs of Moher", lat: 53.014, lng: -9.396, year: 2025, category: "landscape", featured: false },
    { id: 17, src: "/photofolio/norway/DSC00422.JPG", country: "Norway", city: "Tromso", lat: 69.651, lng: 18.915, year: 2026, category: "landscape", featured: false },
    { id: 18, src: "/photofolio/norway/DSC00532.JPG", country: "Norway", city: "Ersfjordbotn", lat: 69.654, lng: 18.91, year: 2026, category: "landscape", featured: false },
    { id: 19, src: "/photofolio/norway/DSC00466.JPG", country: "Norway", city: "Ersfjordbotn", lat: 69.651, lng: 18.915, year: 2026, category: "landscape", featured: false },
    { id: 20, src: "/photofolio/morocco/DSC01323.JPG", country: "Morocco", city: "Sahara Desert", lat: 31.62, lng: -7.59, year: 2026, category: "landscape", featured: false },
    // ARCHITECTURE ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    { id: 21, src: "/photofolio/architecture/DSC01273.JPG", country: "The Netherlands", city: "Leiden", lat: 52.16, lng: 4.48, year: 2025, category: "architecture", featured: false },
    { id: 22, src: "/photofolio/architecture/DSC03575.JPG", country: "Ireland", city: "Dublin", lat: 53.34, lng: -6.26, year: 2025, category: "architecture", featured: false },
    { id: 23, src: "/photofolio/architecture/DSC00750 2.JPG", country: "France", city: "Paris", lat: 48.85, lng: 2.35, year: 2026, category: "architecture", featured: false },
    { id: 24, src: "/photofolio/architecture/DSC00779.JPG", country: "France", city: "Paris", lat: 48.85, lng: 2.35, year: 2026, category: "architecture", featured: false },
    { id: 25, src: "/photofolio/architecture/DSC00787 2.JPG", country: "France", city: "Paris", lat: 48.85, lng: 2.35, year: 2026, category: "architecture", featured: false },
    { id: 26, src: "/photofolio/architecture/DSC00748.JPG", country: "France", city: "Paris", lat: 48.85, lng: 2.35, year: 2026, category: "architecture", featured: false },
    { id: 27, src: "/photofolio/architecture/DSC00791.JPG", country: "France", city: "Paris", lat: 48.85, lng: 2.35, year: 2026, category: "architecture", featured: false },
    { id: 28, src: "/photofolio/architecture/DSC01011.JPG", country: "Morocco", city: "Marrakesh", lat: 31.62, lng: -7.59, year: 2026, category: "architecture", featured: false },
    { id: 29, src: "/photofolio/architecture/DSC01396.JPG", country: "Morocco", city: "Marrakesh", lat: 31.62, lng: -7.59, year: 2026, category: "architecture", featured: false },
    // MACRO ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    { id: 30, src: "/photofolio/macro/DSC00260.JPG", country: "California", city: "Newport Beach", lat: 33.62, lng: -117.94, year: 2025, category: "macro", featured: false },
    { id: 31, src: "/photofolio/macro/DSC00265.JPG", country: "California", city: "Newport Beach", lat: 33.62, lng: -117.94, year: 2025, category: "macro", featured: false },
    { id: 32, src: "/photofolio/macro/DSC03789.JPG", country: "Ireland", city: "Dublin", lat: 53.34, lng: -6.26, year: 2025, category: "macro", featured: false },
    { id: 33, src: "/photofolio/macro/DSC01025.JPG", country: "Morocco", city: "Marrakesh", lat: 31.62, lng: -7.59, year: 2026, category: "macro", featured: false },
    { id: 34, src: "/photofolio/macro/DSC01043.JPG", country: "Morocco", city: "Marrakesh", lat: 31.62, lng: -7.59, year: 2026, category: "macro", featured: false },
    { id: 35, src: "/photofolio/macro/DSC01395.JPG", country: "Morocco", city: "Marrakesh", lat: 31.62, lng: -7.59, year: 2026, category: "macro", featured: false },
];

export default photos;